// packages/demo/src/vue/App.vue
<template>
  <div class="container">
    <h1>Vue Easy Audio Player</h1>
    <EasyAudioPlayer :options="options" :url="url" />
  </div>
</template>

<script setup lang="ts">
import { AudioPlayerOptions } from 'easy-audio-player-shared';
import EasyAudioPlayer from 'easy-audio-player-vue';

const options: AudioPlayerOptions = {
  showDownloadButton: true,
};
const url = '/Richard Wagner - Rienzi Overture.mp3';
</script>

// packages/demo/src/react/App.tsx
import { AudioPlayerOptions } from 'easy-audio-player-shared';
import EasyAudioPlayer from '@hekeh/easy-audio-player-react';

const options: AudioPlayerOptions = {
  showDownloadButton: true,
};
const url = '/Richard Wagner - Rienzi Overture.mp3';

export default function App() {
  return (
    <div className="container" style={{ marginTop: '50px' }}>
      <h1>React Easy Audio Player</h1>
      <EasyAudioPlayer options={options} url={url} />
    </div>
  );
}
