// packages/player-react/src/components/progress.tsx
import { useEffect, useRef, useState } from 'react';
import { formatTime, bem } from 'easy-audio-player-shared';

interface PlayerProgressProps {
  player: HTMLAudioElement | null;
}

const useProcess = (player: HTMLAudioElement | null) => {
  const progressBarRef = useRef<HTMLDivElement>(null);
  const progressBarPinRef = useRef<HTMLDivElement>(null);
  const [currentTime, setCurrentTime] = useState('00:00');
  const [totalTime, setTotalTime] = useState('00:00');
  const [isDragging, setIsDragging] = useState(false);
  const [percent, setPercent] = useState(0);

  const updateProgress = () => {
    if (!player || !progressBarRef.current || isDragging) return;

    const current = player.currentTime;
    const duration = player.duration;
    setPercent(current / duration);
    setCurrentTime(formatTime(current));
  };

  const handleProgressBarClick = (event: React.MouseEvent) => {
    if (!player || !progressBarRef.current?.parentElement) return;

    const bounds = progressBarRef.current.parentElement.getBoundingClientRect();
    const x = event.clientX - bounds.left;
    const width = bounds.width;
    const newPercent = x / width;
    setPercent(newPercent);
    player.currentTime = newPercent * player.duration;
  };

  const handleDraggingProcess = (event: MouseEvent) => {
    if (!player || !progressBarRef.current?.parentElement) return;

    const bounds = progressBarRef.current.parentElement.getBoundingClientRect();
    const x = Math.max(0, Math.min(event.clientX - bounds.left, bounds.width));
    const newPercent = x / bounds.width;
    setPercent(newPercent);
    player.currentTime = newPercent * player.duration;
  };

  const stopDraggingProcess = () => {
    setIsDragging(false);
    document.removeEventListener('mousemove', handleDraggingProcess);
    document.removeEventListener('mouseup', stopDraggingProcess);
  };

  const startDraggingProcess = (event: React.MouseEvent) => {
    event.stopPropagation();
    event.preventDefault();
    setIsDragging(true);
    document.addEventListener('mousemove', handleDraggingProcess);
    document.addEventListener('mouseup', stopDraggingProcess);
  };

  useEffect(() => {
    if (!player) return;

    const handleLoadedMetadata = () => {
      setTotalTime(formatTime(player.duration));
    };

    player.addEventListener('timeupdate', updateProgress);
    player.addEventListener('loadedmetadata', handleLoadedMetadata);

    return () => {
      player.removeEventListener('timeupdate', updateProgress);
      player.removeEventListener('loadedmetadata', handleLoadedMetadata);
      document.removeEventListener('mousemove', handleDraggingProcess);
      document.removeEventListener('mouseup', stopDraggingProcess);
    };
  }, [player]);

  return {
    progressBarRef,
    progressBarPinRef,
    currentTime,
    totalTime,
    percent,
    handleProgressBarClick,
    startDraggingProcess,
  };
};

const PlayerProgress: React.FC<PlayerProgressProps> = ({ player }) => {
  const {
    progressBarRef,
    progressBarPinRef,
    currentTime,
    totalTime,
    percent,
    handleProgressBarClick,
    startDraggingProcess,
  } = useProcess(player);

  return (
    <div className={bem('progress')}>
      <span className={bem('progress', 'current-time')}>{currentTime}</span>
      <div
        className={bem('progress-bar', 'wrapper')}
        onClick={handleProgressBarClick}
      >
        <div className={bem('progress-bar')}>
          <div
            className={bem('progress-bar', 'fill')}
            ref={progressBarRef}
            style={{ width: `${percent * 100}%` }}
          >
            <div
              className={bem('progress-bar', 'pin')}
              ref={progressBarPinRef}
              onMouseDown={startDraggingProcess}
              onDragStart={e => e.preventDefault()}
            />
          </div>
        </div>
      </div>
      <span className={bem('progress', 'total-time')}>{totalTime}</span>
    </div>
  );
};

export default PlayerProgress;

// packages/player-vue/src/components/progress.vue
<template>
  <!-- Progress Bar -->
  <div :class="bem('progress')">
    <span :class="bem('progress', 'current-time')">{{ currentTime }}</span>
    <div
      :class="bem('progress-bar', 'wrapper')"
      @click="handleProgressBarClick"
    >
      <div :class="bem('progress-bar')">
        <div
          :class="bem('progress-bar', 'fill')"
          ref="progressBar"
          :style="{ width: `${percent * 100}%` }"
        >
          <div
            :class="bem('progress-bar', 'pin')"
            ref="progressBarPin"
            @mousedown="startDraggingProcess"
            @dragstart.prevent
          ></div>
        </div>
      </div>
    </div>
    <span :class="bem('progress', 'total-time')">{{ totalTime }}</span>
  </div>
</template>

<script lang="ts">
import {
  defineComponent,
  onBeforeUnmount,
  ref,
  toRef,
  watch,
  type PropType,
  type Ref,
} from 'vue';
import { formatTime } from 'easy-audio-player-shared';
import { bem } from 'easy-audio-player-shared';

const useProcess = (player: Ref<HTMLAudioElement | null>) => {
  const progressBar = ref<HTMLElement | null>(null);
  const progressBarPin = ref<HTMLElement | null>(null);
  const currentTime = ref('00:00');
  const totalTime = ref('00:00');
  const isDragging = ref(false);
  const percent = ref(0);

  const updateProgress = () => {
    if (!player.value || !progressBar.value || isDragging.value) return;

    const current = player.value.currentTime;
    const duration = player.value.duration;
    percent.value = current / duration;

    currentTime.value = formatTime(current);
  };

  const handleProgressBarClick = (event: MouseEvent) => {
    if (!player.value || !progressBar.value?.parentElement) return;

    const bounds = progressBar.value.parentElement.getBoundingClientRect();
    const x = event.clientX - bounds.left;
    const width = bounds.width;
    percent.value = x / width;
    player.value.currentTime = percent.value * player.value.duration;
  };

  const startDraggingProcess = (event: MouseEvent) => {
    event.stopPropagation();
    event.preventDefault();
    isDragging.value = true;
    document.addEventListener('mousemove', handleDraggingProcess);
    document.addEventListener('mouseup', stopDraggingProcess);
  };

  const handleDraggingProcess = (event: MouseEvent) => {
    if (!player.value || !progressBar.value?.parentElement) return;

    const bounds = progressBar.value.parentElement.getBoundingClientRect();
    const x = Math.max(0, Math.min(event.clientX - bounds.left, bounds.width));
    percent.value = x / bounds.width;
    player.value.currentTime = percent.value * player.value.duration;
  };

  const removeDraggingProcessListeners = () => {
    document.removeEventListener('mousemove', handleDraggingProcess);
    document.removeEventListener('mouseup', stopDraggingProcess);
  };

  const stopDraggingProcess = () => {
    isDragging.value = false;
    removeDraggingProcessListeners();
  };

  const playerEvents = {
    timeupdate: updateProgress,
    loadedmetadata: () => {
      totalTime.value = formatTime(player.value?.duration || 0);
    },
  };

  watch(
    () => player.value,
    (newPlayer, oldPlayer) => {
      if (oldPlayer) {
        Object.entries(playerEvents).forEach(([event, handler]) => {
          oldPlayer.removeEventListener(event, handler);
        });
      }
      if (newPlayer) {
        Object.entries(playerEvents).forEach(([event, handler]) => {
          newPlayer.addEventListener(event, handler);
        });
      }
    },
  );

  onBeforeUnmount(() => {
    const playerDom = player.value;
    if (playerDom) {
      Object.entries(playerEvents).forEach(([event, handler]) => {
        playerDom.removeEventListener(event, handler);
      });
    }
    removeDraggingProcessListeners();
  });

  return {
    progressBar,
    progressBarPin,
    currentTime,
    totalTime,
    percent,
    updateProgress,
    handleProgressBarClick,
    startDraggingProcess,
  };
};

const PlayerProgress = defineComponent({
  name: 'PlayerProgress',
  props: {
    player: {
      type: [Object, null] as PropType<HTMLAudioElement | null>,
      required: true,
    },
  },

  setup(props) {
    const {
      progressBar,
      progressBarPin,
      currentTime,
      totalTime,
      percent,
      updateProgress,
      handleProgressBarClick,
      startDraggingProcess,
    } = useProcess(toRef(props, 'player'));

    return {
      progressBar,
      progressBarPin,
      currentTime,
      totalTime,
      percent,
      updateProgress,
      handleProgressBarClick,
      startDraggingProcess,
      bem,
    };
  },
});

export default PlayerProgress;
</script>
