// packages/player-vue/src/main.vue
<template>
  <div :class="namespace" ref="container">
    <div :class="bem('controls')">
      <!-- Play/Pause Button -->
      <button
        :class="[
          bem('pause-btn'),
          { [bem('pause-btn', '', 'loading')]: isLoading },
        ]"
        @click="togglePlay"
        :disabled="isLoading"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 18 24"
          :class="bem('pause-btn', 'icon')"
        >
          <path
            fill-rule="evenodd"
            :d="isPlaying ? 'M0 0h6v24H0zM12 0h6v24h-6z' : 'M18 12L0 24V0'"
          />
        </svg>
      </button>

      <!-- Progress Bar -->
      <player-progress :player="player" />

      <div :class="bem('right-controls')">
        <!-- Volume Controls -->
        <player-volume @update:volume="onUpdateVolume" />
        <!-- Download Button -->
        <button
          v-if="showDownloadButton"
          :class="bem('control-btn')"
          @click="downloadAudio"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            :class="bem('control-btn', 'icon')"
          >
            <path
              fill-rule="evenodd"
              d="M19 9h-4V3H9v6H5l7 8 7-8zM5 18v3h14v-3H5z"
            />
          </svg>
        </button>
      </div>

      <audio ref="player" :src="url" preload="metadata"></audio>
    </div>
  </div>
</template>

<script lang="ts">
import {
  computed,
  defineComponent,
  onBeforeUnmount,
  onMounted,
  ref,
  useId,
  type PropType,
} from 'vue';
import type {
  AudioPlayerOptions,
  EasyAudioPlayerProps,
} from 'easy-audio-player-shared';
import PlayerVolume from './components/volume.vue';
import PlayerProgress from './components/progress.vue';
import { namespace, bem } from 'easy-audio-player-shared';

const EasyAudioPlayer = defineComponent({
  name: 'EasyAudioPlayer',
  components: {
    PlayerVolume,
    PlayerProgress,
  },

  props: {
    url: {
      type: String,
      required: true,
    },
    options: {
      type: Object as PropType<AudioPlayerOptions>,
      default: () => ({}),
    },
  },

  setup(props: EasyAudioPlayerProps) {
    const container = ref<HTMLElement | null>(null);
    const player = ref<HTMLAudioElement | null>(null);
    const isPlaying = ref(false);
    const isLoading = ref(false);
    const { stopOthersOnPlay = true } = props.options;

    const onUpdateVolume = (volume: number) => {
      if (!player.value) return;
      player.value.volume = volume;
    };

    const closePlayer = () => {
      player.value?.pause();
      isPlaying.value = false;
    };

    const { stopOtherPlayers } = useStopOtherPlayers(closePlayer);

    const togglePlay = async () => {
      if (!player.value) return;

      try {
        if (player.value.paused) {
          if (stopOthersOnPlay) {
            stopOtherPlayers();
          }
          isLoading.value = true;
          await player.value.play();
          isPlaying.value = true;
        } else {
          closePlayer();
        }
      } catch (error) {
        console.error('Play fail:', error);
      } finally {
        isLoading.value = false;
      }
    };

    const playerEvents = {
      waiting: () => {
        isLoading.value = true;
      },
      canplay: () => {
        isLoading.value = false;
      },
    };

    onMounted(() => {
      if (!player.value) return;
      Object.entries(playerEvents).forEach(([event, handler]) => {
        player.value?.addEventListener(event, handler);
      });
    });

    onBeforeUnmount(() => {
      if (!player.value) return;

      Object.entries(playerEvents).forEach(([event, handler]) => {
        player.value?.removeEventListener(event, handler);
      });
    });
    const downloadAudio = () => {
      const link = document.createElement('a');
      link.href = props.url;
      link.download = props.url.split('/').pop() || 'audio';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    };
    return {
      container,
      player,
      isPlaying,
      isLoading,
      showDownloadButton: computed(
        () => props.options.showDownloadButton ?? true,
      ),
      namespace,
      togglePlay,
      downloadAudio,
      onUpdateVolume,
      bem,
    };
  },
});

const useStopOtherPlayers = (closePlayer: () => void) => {
  const EventName = 'stop-easy-audio-player';
  const id = useId();
  const stopOtherPlayers = () => {
    document.dispatchEvent(
      new CustomEvent(EventName, {
        detail: { excludedId: id },
      }),
    );
  };

  const stopOtherPlayersHandler = (
    event: CustomEvent<{
      excludedId: string;
    }>,
  ) => {
    if (event.detail.excludedId === id) return;
    closePlayer();
  };

  onMounted(() => {
    document.addEventListener(
      EventName,
      stopOtherPlayersHandler as EventListener,
    );
  });
  onBeforeUnmount(() => {
    document.removeEventListener(
      EventName,
      stopOtherPlayersHandler as EventListener,
    );
  });
  return { stopOtherPlayers };
};

export default EasyAudioPlayer;
</script>

// packages/player-react/src/main.tsx
import { EasyAudioPlayerProps, bem, namespace } from 'easy-audio-player-shared';
import React, { useCallback, useEffect, useId, useRef, useState } from 'react';

import PlayerProgress from './components/progress';
import PlayerVolume from './components/volume';

type EventListener = (event: Event) => void;

const useStopOtherPlayers = (closePlayer: () => void) => {
  const EventName = 'stop-easy-audio-player';
  const id = useId();

  const stopOtherPlayers = useCallback(() => {
    document.dispatchEvent(
      new CustomEvent(EventName, {
        detail: { excludedId: id },
      }),
    );
  }, [id]);

  const stopOtherPlayersHandler = useCallback(
    (event: CustomEvent<{ excludedId: string }>) => {
      if (event.detail.excludedId === id) {
        return;
      }
      closePlayer();
    },
    [closePlayer, id],
  );

  useEffect(() => {
    document.addEventListener(
      EventName,
      stopOtherPlayersHandler as EventListener,
    );
    return () => {
      document.removeEventListener(
        EventName,
        stopOtherPlayersHandler as EventListener,
      );
    };
  }, [stopOtherPlayersHandler]);

  return { stopOtherPlayers };
};

const EasyAudioPlayer: React.FC<EasyAudioPlayerProps> = ({
  url,
  options = {},
}) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const playerRef = useRef<HTMLAudioElement>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const { stopOthersOnPlay = true, showDownloadButton = true } = options;

  const onUpdateVolume = useCallback((volume: number) => {
    if (!playerRef.current) {
      return;
    }
    playerRef.current.volume = volume;
  }, []);

  const closePlayer = useCallback(() => {
    playerRef.current?.pause();
    setIsPlaying(false);
  }, []);

  const { stopOtherPlayers } = useStopOtherPlayers(closePlayer);

  const togglePlay = useCallback(async () => {
    if (!playerRef.current) {
      return;
    }

    try {
      if (playerRef.current.paused) {
        if (stopOthersOnPlay) {
          stopOtherPlayers();
        }
        setIsLoading(true);
        await playerRef.current.play();
        setIsPlaying(true);
      } else {
        closePlayer();
      }
    } catch (error) {
      console.error('Play fail:', error);
    } finally {
      setIsLoading(false);
    }
  }, [closePlayer, stopOtherPlayers, stopOthersOnPlay]);

  useEffect(() => {
    const player = playerRef.current;
    if (!player) {
      return;
    }

    const onWaiting = () => setIsLoading(true);
    const onCanPlay = () => setIsLoading(false);

    player.addEventListener('waiting', onWaiting);
    player.addEventListener('canplay', onCanPlay);

    return () => {
      player.removeEventListener('waiting', onWaiting);
      player.removeEventListener('canplay', onCanPlay);
    };
  }, []);

  const downloadAudio = useCallback(() => {
    const link = document.createElement('a');
    link.href = url;
    link.download = url.split('/').pop() || 'audio';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }, [url]);

  return (
    <div className={namespace} ref={containerRef}>
      <div className={bem('controls')}>
        <button
          className={`${bem('pause-btn')} ${
            isLoading ? bem('pause-btn', '', 'loading') : ''
          }`}
          onClick={togglePlay}
          disabled={isLoading}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 18 24"
            className={bem('pause-btn', 'icon')}
          >
            <path
              fillRule="evenodd"
              d={isPlaying ? 'M0 0h6v24H0zM12 0h6v24h-6z' : 'M18 12L0 24V0'}
            />
          </svg>
        </button>

        <PlayerProgress player={playerRef.current} />

        <div className={bem('right-controls')}>
          <PlayerVolume onVolumeChange={onUpdateVolume} />
          {showDownloadButton && (
            <button className={bem('control-btn')} onClick={downloadAudio}>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                className={bem('control-btn', 'icon')}
              >
                <path
                  fillRule="evenodd"
                  d="M19 9h-4V3H9v6H5l7 8 7-8zM5 18v3h14v-3H5z"
                />
              </svg>
            </button>
          )}
        </div>

        <audio ref={playerRef} src={url} preload="metadata" />
      </div>
    </div>
  );
};

export default EasyAudioPlayer;
